version: 0.2

phases:
  pre_build:
    commands:
      - cd docker/alignment/ && bash build.sh quay.io wgspipelinetest $QUAY_USR $QUAY_PSW && cd ../../
      - cd docker/copynumber/ && bash build.sh quay.io wgspipelinetest $QUAY_USR $QUAY_PSW && cd ../../ 
      - cd docker/breakpoint/ && bash build.sh quay.io wgspipelinetest $QUAY_USR $QUAY_PSW && cd ../../
      - cd docker/germline/ && bash build.sh quay.io wgspipelinetest $QUAY_USR $QUAY_PSW && cd ../../
      - cd docker/somatic/ && bash build.sh quay.io wgspipelinetest $QUAY_USR $QUAY_PSW && cd ../../

  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/alignment/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/copynumber/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/breakpoint/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/germline/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/somatic/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then cd docker/qc/ && bash build.sh quay.io wgspipeline $QUAY_USR $QUAY_PSW && cd ../../; fi
