FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2

ADD . /app

RUN apt-get update \
    && wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.7_all.deb -P ~/Downloads \
    && apt install ~/Downloads/ttf-mscorefonts-installer_3.7_all.deb -y \
    && apt-mark hold ttf-mscorefonts-installer && rm -rf /var/lib/apt/lists/*


RUN conda install -c dranew remixt && rm -rf /opt/conda/lib/python2.7/site-packages/remixt*
RUN apt-get update && apt-get install libc-dev libz-dev -y && apt-get install build-essential -y && rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython
RUN rm -rf /opt/conda/lib/python2.7/site-packages/pypeliner*
RUN pip install git+https://github.com/amcpherson/remixt.git@master

RUN conda install -c bioconda vcftools tabix bcftools snpeff
RUN conda install -c bioconda perl-vcftools-vcf==0.1.15


RUN conda create --name titan python=2.7
SHELL ["conda", "run", "-n", "titan", "/bin/bash", "-c"]
RUN conda install --file /app/titan.csv
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN conda create --name hmmcopy python=2.7
SHELL ["conda", "run", "-n", "hmmcopy", "/bin/bash", "-c"]
RUN conda install --file /app/hmmcopy.csv
RUN cp /app/*.R /opt/conda/envs/hmmcopy/bin
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN conda create --name museq python=2.7
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install -c conda-forge -c shahcompbio museq intervaltree museqportrait==0.99.13 -y
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@master
RUN pip install git+https://github.com/shahcompbio/wgs.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@master
RUN pip install git+https://github.com/shahcompbio/wgs_qc_utils.git@v0.0.5
RUN pip install git+https://github.com/shahcompbio/classifycopynumber.git@v0.0.2
RUN pip install git+https://github.com/amcpherson/wgs_analysis.git@v0.0.1
RUN pip install pyvcf intervaltree fpdf
RUN pip install PyPDF2==1.26.0

ENV PATH="${PATH}:/opt/conda/envs/titan/bin:/opt/conda/envs/hmmcopy/bin:/opt/conda/envs/museq/bin"

