FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2

ADD . /app

RUN conda install --file /app/conda_requirements.yml
RUN pip install -r /app/requirements.txt


RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.5.29
RUN pip install git+https://github.com/shahcompbio/wgs.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/wgs_qc_utils.git@v0.0.5
