FROM quay.io/wgspipeline/singularity_base:v0.0.1

ADD . /app

RUN conda install -c bioconda -c conda-forge samtools cryptography
RUN conda install -c bioconda -c conda-forge bcftools cryptography
RUN conda install -c bioconda gatk4
RUN cp /app/run_strelka /opt/conda/bin && chmod 777 /opt/conda/bin/run_strelka
RUN conda install -c shahcompbio -c bioconda vcf2maf_shahcompbio

RUN conda create --name museq python=2.7
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install -c conda-forge -c shahcompbio museq intervaltree museqportrait==0.99.13 -y
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN conda create --name strelka python=2.7
SHELL ["conda", "run", "-n", "strelka", "/bin/bash", "-c"]
RUN conda install -c aroth85 strelka
RUN conda install -c conda-forge intervaltree
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]


RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner*
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@master
RUN pip install git+https://github.com/shahcompbio/wgs.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@master
RUN pip install git+https://github.com/shahcompbio/wgs_qc_utils.git@v0.0.5
RUN pip install git+https://github.com/shahcompbio/classifycopynumber.git@v0.0.2
RUN pip install git+https://github.com/amcpherson/wgs_analysis.git@v0.0.1

ENV PATH="${PATH}:/opt/conda/envs/museq/bin:/opt/conda/envs/strelka/share/strelka-2.8.2-0/libexec/"
ENV STRELKA_SHARE_DIR '/opt/conda/envs/strelka/share/strelka-2.8.2-0/'
